version: '3.8'

services:
  dev:
    build: .
    container_name: tracking-algorithms-in-sports
    volumes:
      - ./:/app/main
    working_dir: /app/main
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    shm_size: 40G
    environment:
      WANDB_API_KEY: $WANDB_API_KEY
